version: '3.9'

services:
  mcrcon:
    container_name: 'mcrcon'
    build:
      context: '../docker-minecraft-server/src/mcrcon'
      dockerfile: 'Containerfile'
    entrypoint: 'echo done'
  minecraft-server:
    container_name: 'minecraft-server'
    build:
      context: '../docker-minecraft-server'
      dockerfile: 'src/servers/papermc/Containerfile'
      args:
        MCRCON_IMAGE: 'docker-compose-minecraft_mcrcon'
    environment:
      MINECRAFT_VERSION: 'release'
      EULA: 'true'
      RAM_MAX: '8G'
    env_file: '.env'
    volumes:
      - '/usr/local/etc/minecraft-server-data:/data'
      - '/usr/local/lib/minecraft-server-jars:/server-jars'
    ports:
      - '25565:25565/tcp'
      - '25565:25565/udp'
      - '8123:8123' # dynmap http
    deploy:
      resources:
        limits:
          memory: 10G
    restart: 'unless-stopped'
